### PR TITLE
Analysis and Github Action

### LINKED ISSUE #11: Initial GitHub action
The GitHub action should

 * use node 18
 * execute the HTML generation script(s)
 * execute the JSON generation scripts

### PR DESCRIPTION
**Pull request by Nashtronaut**
Hey @aaronfay!

Here is the working script for the analysis, or at least a solid starting point for some adjustments!

First, we check if we have the right directories and such, clear them out with a new function, and then create empty ones to run the full parse again.

The results are the original `json` folder containing `pct-#.json` files. 

In addition, we now have an `errors` folder that will contain `pct-#-errors.json` files.

### Error structure

```
// filename: pct-1-errors.json
[...
  {
    surface: canonical,
    nodePosition: {
      line: #,
      column: #
    },
    results: full results with Err/Frags
  }
...]
```

### Good analysis structure

```
// node json
...
analysis: ['result from fst']
...
```

EDIT:

### Github Action 

Please note I have now included a new github actions that runs on branch push, runs the script automatically, and then commits the newly generated files to that branch.

Some key information on this action.

- runs node 18.x
- runs on push, so if you add new stories it will run when you push them.
- commits changes directly to the branch that they were pushed too
- only commits if a git diff is detected between the current remote and the newly ran script.

[You can view said action here.](https://github.com/kiyanaw/bloomfield/pull/14/files#diff-a93bf04c4a65e52f71a40caf004d65828168302d5659ef45b99f2c45042262a4)

Also, since we are adding all the JSON files in this PR, here are the relevant NOT auto generated files. 

[`.gitignore`](https://github.com/kiyanaw/bloomfield/pull/14/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947)

[`bulk-parse`](https://github.com/kiyanaw/bloomfield/pull/14/files#diff-65e7fcc4c58f60b0a5a572176e0b4203e5124694cf53fe955e7e51fe5de35566)

[`parse-json`]( https://github.com/kiyanaw/bloomfield/pull/14/files#diff-1cf79c1612df9190c7e9c77b1bdb54f4bd7b35111c8be974dae9d9356323f988)

Fixes #11 and #12

### CODE REVIEW

**Comment by aaronfay** [comment]
Very nice! 

One thing I'd like to change is the line/column details of the errors:

```
{
  "surface": "kêkway",
  "nodePosition": { "line": 73, "column": 74 },
  "results": [
    "IC+PV/kakwe+_+Cnj+Err/Frag",
    "IC+PV/kakwe+_+Cnj+Err/Frag",
    "IC+PV/kakwe+_+Cnj+Err/Frag",
    "IC+PV/kakwe+_+Cnj+Err/Frag",
    "IC+PV/kakwe+_+Cnj+Err/Frag",
    "IC+PV/kakwe+_+Cnj+Err/Frag",
    "IC+PV/kakwe+_+Cnj+Err/Frag"
  ]
}

```

The `nodePosition` should be just `location` and the values should be the paragraph and sentence, so something like 

```
  "location": {"paragraph": 2, "sentence": 2.3}
```

Also, the `results` field can just be omitted, it's not necessary.

Last, the `analysis` on the other files looks like it's coming through empty (eg: `{},{},{},{},{},{},{}`): 

```
[{"id":"1","sentences":[{"id":"1.1","original":"pêyak âcimôw kisêyiniw; oskahocâs isiyîhkâsôw.","text":"pêyak âcimôw kisêyiniw oskahocâs isiyîhkâsôw","english":"A certain old man told this tale; Uskahutchas was his name.","analysis":[{},{},{},{},{},{},{},{},{},{},{},{},{}]}]}
```

Nice work so far!

**Comment by Nashtronaut** [comment]
> Very nice!
> 
> One thing I'd like to change is the line/column details of the errors:
> 
> ```
> {
>   "surface": "kêkway",
>   "nodePosition": { "line": 73, "column": 74 },
>   "results": [
>     "IC+PV/kakwe+_+Cnj+Err/Frag",
>     "IC+PV/kakwe+_+Cnj+Err/Frag",
>     "IC+PV/kakwe+_+Cnj+Err/Frag",
>     "IC+PV/kakwe+_+Cnj+Err/Frag",
>     "IC+PV/kakwe+_+Cnj+Err/Frag",
>     "IC+PV/kakwe+_+Cnj+Err/Frag",
>     "IC+PV/kakwe+_+Cnj+Err/Frag"
>   ]
> }
> ```
> 
> The `nodePosition` should be just `location` and the values should be the paragraph and sentence, so something like
> 
> ```
>   "location": {"paragraph": 2, "sentence": 2.3}
> ```
> 
> Also, the `results` field can just be omitted, it's not necessary.
> 
> Last, the `analysis` on the other files looks like it's coming through empty (eg: `{},{},{},{},{},{},{}`):
> 
> ```
> [{"id":"1","sentences":[{"id":"1.1","original":"pêyak âcimôw kisêyiniw; oskahocâs isiyîhkâsôw.","text":"pêyak âcimôw kisêyiniw oskahocâs isiyîhkâsôw","english":"A certain old man told this tale; Uskahutchas was his name.","analysis":[{},{},{},{},{},{},{},{},{},{},{},{},{}]}]}
> ```
> 
> Nice work so far!

Oh my goodness my apologies, I was so focused on reviewing a single one that I missed that. I will fix that right away. 

What did you think about the action as well? Is there anything you'd like to adjust there?

**Comment by Nashtronaut** [comment]
I am scrolling through the diff and am now realizing how painfully obvious the `{}{}{}` is. I really apologize for missing that.

**Comment by aaronfay** [comment]
The action looks great 👌🏻

**Review by aaronfay — APPROVED** [review]
This is great, nice work 👌🏻

**Pull request merged**
